language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"

# The following are currently not supported:
#  - "0.10"
#  - "0.8"
#  - "0.6"

notifications:
  email: false

install:
  - npm install
  - npm install redis@2.6.0-1

services:
  - redis-server
